version: '2'

services:

  postgresql:
    image: "postgres:16.0"
    # ports:
    #   - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=gochat
      - POSTGRES_USER=gochat
      - POSTGRES_DB=gochat
    profiles:
      - all
      - db
      - initdb

  auth:
    image: "spring-auth:latest"
    build: ./auth
    volumes:
      - ./keys/private_key.der:/app/private_key.der
      - ./keys/public_key.der:/app/public_key.der
    environment:
      - SERVER_PORT=9999
      - POSTGRES_PASSWORD=gochat
      - POSTGRES_USER=gochat
      - POSTGRES_DB=gochat
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - PRIVKEY_FILEPATH=/app/private_key.der
      - PUBKEY_FILEPATH=/app/public_key.der
    depends_on:
      - postgresql
    profiles:
      - all
  
  chatserver:
    image: "chat-server:latest"
    build: ./chat-server
    volumes:
      - ./keys/public_key.der:/app/public_key.der
    environment:
      - POSTGRES_PASSWORD=gochat
      - POSTGRES_USER=gochat
      - POSTGRES_DB=gochat
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - SERVER_HOST=chatserver
      - SERVER_PORT=9000
      - JWTKEY_FILENAME=/app/public_key.der
    depends_on:
      - postgresql
      - auth
    profiles:
      - all

  webapp:
    image: "webapp:latest"
    build: ./webapp
    volumes:
      - ./keys/public_key.der:/app/public_key.der
    environment:
      - POSTGRES_PASSWORD=gochat
      - POSTGRES_USER=gochat
      - POSTGRES_DB=gochat
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - JWTKEY_FILENAME=/app/public_key.der
    depends_on:
      - postgresql
      - auth
      - chatserver
    profiles:
      - all

  nginx:
    image: "nginx:1.25-alpine"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    profiles:
      - all

  initdb:
    image: alpine:3.18
    volumes:
      - ./db:/tmp/db
    command: /bin/sh -c
      'apk --update add postgresql-client &&
      echo "*:*:gochat:gochat:gochat" > /tmp/.pgpass &&
      chmod 600 /tmp/.pgpass &&
      cd /tmp/db &&
      PGPASSFILE=/tmp/.pgpass psql -h postgresql -U gochat -a -f init.sql'
    depends_on:
      - postgresql
    profiles:
      - initdb

volumes:
  db: