version: '2'

services:
  postgresql:
    image: "postgres:16.0"
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=gochat
      - POSTGRES_USER=gochat
      - POSTGRES_DB=gochat


volumes:
  db: