version: '2'

services:
  postgresql:
    image: "postgres:16.0"
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=gochat
      - POSTGRES_USER=gochat
      - POSTGRES_DB=gochat

  auth:
    image: "spring-auth:latest"
    ports:
      - 9999:9999
    environment:
      - SERVER_PORT=9999
      - POSTGRES_PASSWORD=gochat
      - POSTGRES_USER=gochat
      - POSTGRES_DB=gochat
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432

volumes:
  db: